### ISSUE TITLE
Floating point operation bug

### ISSUE THREAD

**Issue by AlpBilgin** [williambl/bigbuckets#2]
Some of my buckets have X.035 amount of fluid in them. Could it be a FP arithmetic bug?

**Comment by williambl** [comment]
No, the big bucket holds an integer amount of millibuckets. It is only displayed as a decimal amount of buckets.

**Comment by AlpBilgin** [comment]
Well this is probably a moot point, I stopped playing and archived my server.

Close it up if you think it isn't important. It made my life a bit hard because I couldn't get rid of the last 0.035 fraction and my big buckets suddenly became typed based on the fractional liquid inside.
