### ISSUE TITLE
[1.16.1] Big Bucket is consumed in bulk-recipe crafts

### ISSUE THREAD

**Issue by NielsPilgaard** [williambl/bigbuckets#5]
In recipes that take buckets of liquid, such as the Immersive Engineering Treated Wood Planks recipe, the Big Bucket can be used if it contains the correct fluid. However, the Big Bucket will be consumed completely, and only 1 set of the recipe will be triggered. 

### Version
- Forge-1.16.1-32.0.108
- bigbuckets-1.1.1

**Comment by williambl** [comment]
Should be fixed in 1.1.3. Note that 1.1.3 is 1.16.2 only, as there were breaking changes between Minecraft 1.16.1 and 1.16.2.

**Comment by NielsPilgaard** [comment]
Cool, thanks :)
